version: 2
jobs:
  deploy:
    docker:
      - image: turtlog/node-awscli:nuxt-1.0
    working_directory: ~/repo
    steps:
      - checkout
      # Deploy files!
      - run: npm i
      - run:
          command: npm run generate
          environment:
            NODE_ENV: production
      - run: aws s3 cp ./dist s3://study-nuxt.ml/ --acl public-read --recursive
      # - run:
      #     command: aws cloudfront create-invalidation
      #             --distribution-id EA8V5H12G53MS
      #             --paths /index.html /app.js
workflows:
  version: 2
  turtlog.ml:
    jobs:
      - deploy:
          filters:
              branches:
                only: master